[build]
  # This is for single-page applications (SPA)
  # All routes should serve index.html
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Production optimizations
  NODE_ENV = "production"

# Optional: Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"